---
- name: "install system software"
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items: "{{ software_packages_list }}"
  tags:
    - dependent-software
